// Industry-specific configurations
// NOTE: Universal content (About page, team, values) moved to universal-content.ts

import type { IndustryConfig, IndustryType } from '../types/Industry';

// Base configuration that all industries inherit from
const baseConfig = {
  features: {
    blog: false,
    aiWriter: true,
    imageGeneration: true,
    analytics: true,
  },
};

// Default configurations for each industry
export const defaultIndustryConfigs: Record<IndustryType, IndustryConfig> = {
  hospitality: {
    ...baseConfig,
    industry: 'hospitality',
    name: 'Hotels & Hospitality Marketing',
    subdomain: 'hotels',
    branding: {
      primaryColor: '#002643',
      secondaryColor: '#0093a0',
      accentColor: '#FFD700',
    },
    content: {
      hero: {
        title: 'Transform Your Hotel\'s Digital Presence',
        subtitle: 'Drive direct bookings and reduce OTA dependency with proven advertising strategies',
        backgroundType: 'video',
        backgroundSrc: 'https://www.youtube.com/watch?v=cAyEiF7VzhY',
        ctaText: 'Get Free Hotel Marketing Audit',
        ctaLink: '/contact',
        stats: [
          { value: '40%', label: 'Increase in Direct Bookings' },
          { value: '25%', label: 'Reduction in OTA Commissions' },
          { value: '60%', label: 'Better ROI vs Traditional Marketing' },
        ],
      },
      // HOMEPAGE - Brief overview content only (hooks to drive to Services page)
      services: [
        {
          title: 'Google Hotel Ads',
          description: 'Capture guests at the exact moment they\'re ready to book with AI-optimized campaigns.',
          keyBenefit: 'Reduce OTA dependency by 35%',
          icon: 'hotel',
          learnMoreLink: '/services#google-hotel-ads',
        },
        {
          title: 'Meta Advertising for Hotels',
          description: 'Build awareness and drive bookings with visual storytelling that showcases your property.',
          keyBenefit: '50% lower cost per booking vs OTAs',
          icon: 'camera',
          learnMoreLink: '/services#meta-advertising',
        },
        {
          title: 'Email Marketing & CRM',
          description: 'Turn one-time guests into loyal repeat customers with automated guest journey campaigns.',
          keyBenefit: '25% increase in repeat bookings',
          icon: 'mail',
          learnMoreLink: '/services#email-marketing',
        },
      ],
      team: [
        {
          name: 'Laurie Meiring',
          title: 'Founder & Hotel Marketing Strategist',
          bio: 'With 15+ years of experience in hospitality marketing, Laurie specializes in helping hotels reduce OTA dependency and maximize direct bookings through strategic digital advertising campaigns.',
          certifications: ['Google Hotel Ads Certified', 'Meta Blueprint Certified'],
          image: '/images/team/laurie-meiring.jpg',
        },
      ],
      testimonials: [
        {
          quote: 'Laurie\'s Google Hotel Ads strategy helped us reduce OTA commissions by 30% while increasing direct bookings by 45%. Our revenue per available room improved significantly.',
          author: 'Sarah Mitchell',
          position: 'General Manager',
          company: 'Oceanview Resort Miami',
        },
        {
          quote: 'Working with Inteligencia transformed our digital presence. We went from 60% OTA bookings to 60% direct bookings in just 6 months. The ROI has been incredible.',
          author: 'David Chen',
          position: 'Owner',
          company: 'Boutique Hotel Downtown',
        },
        {
          quote: 'The email marketing campaigns Laurie created for our hotel generated over $200K in additional revenue this year alone. The guest retention improvements have been remarkable.',
          author: 'Rachel Green',
          position: 'Marketing Director',
          company: 'Downtown Suites Hotel',
        },
      ],
      pricing: {
        plans: [
          {
            name: 'Starter Package',
            price: '$1,500',
            duration: 'per month',
            description: 'Perfect for boutique hotels (1-50 rooms) looking to reduce OTA dependency',
            features: ['Google Hotel Ads setup', 'Basic website optimization', 'Monthly performance reports'],
            ctaText: 'Get Started',
            ctaLink: '/contact',
          },
          {
            name: 'Growth Package',
            price: '$3,000',
            duration: 'per month',
            description: 'Designed for mid-size hotels (50-200 rooms) with multiple revenue streams',
            features: ['Full advertising suite', 'Email marketing automation', 'Revenue optimization', 'Dedicated account manager'],
            recommended: true,
            ctaText: 'Most Popular',
            ctaLink: '/contact',
          },
          {
            name: 'Pro+ Package',
            price: '$5,500',
            duration: 'per month',
            description: 'Built for large hotels (200+ rooms) or resort properties',
            features: ['Enterprise advertising strategy', 'Advanced automation suite', 'Custom integrations', 'Priority support & consulting'],
            ctaText: 'Contact Us',
            ctaLink: '/contact',
          },
        ],
      },
      contact: {
        title: 'Ready to Transform Your Hotel\'s Performance?',
        subtitle: 'Get your free hotel marketing audit and discover how to reduce OTA dependency while increasing direct bookings.',
        calendlyText: 'Schedule Your Free Hotel Marketing Consultation',
        email: 'hotels@inteligencia.com',
        phone: '(555) 123-4567',
        address: '123 Business Ave, Suite 100, Miami, FL 33101',
        businessTypes: ['Boutique Hotel', 'Resort', 'Bed & Breakfast', 'Vacation Rental', 'Hotel Chain', 'Other'],
        budgetRanges: ['$1,000 - $2,500/month', '$2,500 - $5,000/month', '$5,000 - $10,000/month', '$10,000+ /month', 'Let\'s discuss'],
        timelineOptions: ['ASAP - I need help now', 'Within 1 month', '1-3 months', '3-6 months', 'Just exploring options'],
        formLabels: {
          contactMethodsTitle: 'Get in Touch',
          contactMethodsSubtitle: 'Ready to discuss your hospitality marketing goals? Choose the contact method that works best for you.',
          formTitle: 'Send us a message',
          formSubtitle: 'Fill out the form below and we\'ll get back to you within 24 hours with a customized strategy for your business.',
          firstName: 'First Name *',
          lastName: 'Last Name *',
          email: 'Email Address *',
          phone: 'Phone Number',
          company: 'Business Name *',
          businessType: 'Business Type *',
          budget: 'Marketing Budget',
          timeline: 'Timeline',
          goals: 'What are your main marketing goals? *',
          message: 'Additional Details',
          submitButton: 'Send Message & Get Free Consultation',
          privacyText: 'We respect your privacy and will never share your information.',
          placeholders: {
            firstName: 'Enter your first name',
            lastName: 'Enter your last name',
            email: 'your@email.com',
            phone: '(555) 123-4567',
            company: 'Your Business Name',
            businessType: 'Select your business type',
            budget: 'Select your budget range',
            timeline: 'When do you want to start?',
            goals: 'e.g., Increase bookings, drive more customers, improve online presence...',
            message: 'Tell us more about your business, current challenges, or any specific questions you have...'
          }
        },
        officeHours: {
          weekdays: '9:00 AM - 6:00 PM EST',
          saturday: '10:00 AM - 2:00 PM EST', 
          sunday: 'Closed',
          emergency: 'Emergency support available 24/7 for existing clients.',
        },
        faq: [
          {
            question: 'How quickly can I expect to see results?',
            answer: 'Most hotel clients see initial improvements within 30-60 days, with significant direct booking increases typically achieved within 3-6 months. The timeline depends on your current marketing foundation and campaign objectives.',
          },
          {
            question: 'Do you work with hotels outside of these industries?',
            answer: 'We focus exclusively on hospitality, food service, healthcare, and athletics to provide the deepest expertise possible. This specialization allows us to deliver superior results compared to generalist agencies.',
          },
          {
            question: 'What makes your approach different for hotels?',
            answer: 'Unlike generic marketing agencies, we understand the unique challenges of hotel marketing, including OTA dependency, seasonal demand, and direct booking optimization. Our strategies are built on hospitality-specific insights and proven best practices.',
          },
          {
            question: 'Do you require long-term contracts?',
            answer: 'We offer both monthly and annual plans. While we recommend longer commitments for best results, we understand every hotel has different needs and can work with you to find the right arrangement.',
          },
        ],
      },
    },
    metadata: {
      title: 'Hotel Marketing Services - Inteligencia',
      description: 'Professional digital marketing services for hotels and hospitality businesses. Increase direct bookings with Google Hotel Ads, social media, and email marketing.',
      keywords: ['hotel marketing', 'hospitality marketing', 'google hotel ads', 'direct bookings', 'hotel social media'],
    },
  },

  foodservice: {
    ...baseConfig,
    industry: 'foodservice',
    name: 'Restaurant & Food Service Marketing',
    subdomain: 'restaurants',
    branding: {
      primaryColor: '#002643',
      secondaryColor: '#0093a0',
      accentColor: '#FFD700',
    },
    content: {
      hero: {
        title: 'Fill Every Table, Every Night',
        subtitle: 'Drive foot traffic and online orders with restaurant marketing that actually works',
        backgroundType: 'video',
        backgroundSrc: 'https://www.youtube.com/watch?v=cAyEiF7VzhY',
        ctaText: 'Get Free Restaurant Marketing Analysis',
        ctaLink: '/contact',
        stats: [
          { value: '65%', label: 'Increase in Reservations' },
          { value: '80%', label: 'Growth in Online Orders' },
          { value: '3.5x', label: 'Return on Ad Spend' },
        ],
      },
      services: [
        {
          title: 'Local SEO & Google My Business',
          description: 'Dominate local search when hungry customers are looking for a place to eat.',
          keyBenefit: 'Average 45% increase in walk-ins',
          icon: 'map-pin',
          learnMoreLink: '/services#local-seo',
        },
        {
          title: 'Social Media Advertising',
          description: 'Make mouths water with food photography and campaigns that drive orders.',
          keyBenefit: '60% increase in social media orders',
          icon: 'camera',
          learnMoreLink: '/services#social-media',
        },
        {
          title: 'Delivery Platform Management',
          description: 'Optimize your presence on delivery platforms while reducing commission fees.',
          keyBenefit: '30% reduction in delivery fees',
          icon: 'shopping-bag',
          learnMoreLink: '/services#delivery-optimization',
        },
      ],
      team: [
        {
          name: 'Laurie Meiring',
          title: 'Founder & Restaurant Marketing Expert',
          bio: 'Passionate about helping restaurant owners build thriving businesses, Laurie combines culinary industry knowledge with proven digital marketing strategies to fill tables and grow customer loyalty.',
          certifications: ['Google Ads Certified', 'Meta Blueprint Certified', 'Local SEO Expert'],
          image: '/images/team/laurie-meiring.jpg',
        },
      ],
      testimonials: [
        {
          quote: 'Working with Inteligencia completely transformed our restaurant\'s digital presence. We went from empty tables to full reservations, and our online orders tripled in just 4 months.',
          author: 'Maria Rodriguez',
          position: 'Owner & Head Chef',
          company: 'Bella Vista Italian Bistro',
        },
        {
          quote: 'Laurie\'s social media campaigns showcasing our dishes brought in so many new customers. Our Instagram following grew by 400% and foot traffic increased by 65%.',
          author: 'Antonio Ricci',
          position: 'Restaurant Manager',
          company: 'Ricci\'s Family Restaurant',
        },
        {
          quote: 'Our delivery orders increased by 80% after Laurie optimized our presence on all the major platforms. The commission savings alone paid for the marketing investment.',
          author: 'Sofia Martinez',
          position: 'Co-Owner',
          company: 'Martinez Brothers Cantina',
        },
      ],
      pricing: {
        plans: [
          {
            name: 'Essential Package',
            price: '$1,500',
            duration: 'per month',
            description: 'Ideal for single-location restaurants wanting to increase local visibility',
            features: ['Google My Business optimization', 'Social media setup', 'Local SEO optimization'],
            ctaText: 'Get Started',
            ctaLink: '/contact',
          },
          {
            name: 'Professional Package',
            price: '$3,000',
            duration: 'per month',
            description: 'Perfect for restaurant groups or high-volume establishments',
            features: ['Multi-platform campaigns', 'Delivery platform optimization', 'Staff training support', 'Menu and pricing strategy'],
            recommended: true,
            ctaText: 'Most Popular',
            ctaLink: '/contact',
          },
          {
            name: 'Enterprise Package',
            price: '$5,500',
            duration: 'per month',
            description: 'Designed for restaurant chains or flagship locations',
            features: ['Multi-location management', 'Corporate account management', 'Franchise support systems', 'Advanced analytics & reporting'],
            ctaText: 'Contact Us',
            ctaLink: '/contact',
          },
        ],
      },
      contact: {
        title: 'Let\'s Fill Your Restaurant Tonight',
        subtitle: 'Get your free restaurant marketing analysis and learn how to increase foot traffic and online orders.',
        calendlyText: 'Schedule Your Free Restaurant Consultation',
        email: 'restaurants@inteligencia.com',
        phone: '(555) 123-4567',
        address: '123 Business Ave, Suite 100, Miami, FL 33101',
        businessTypes: ['Fine Dining', 'Casual Dining', 'Fast Casual', 'Coffee Shop', 'Bar/Pub', 'Food Truck', 'Restaurant Chain', 'Other'],
        budgetRanges: ['$1,000 - $2,500/month', '$2,500 - $5,000/month', '$5,000 - $10,000/month', '$10,000+ /month', 'Let\'s discuss'],
        timelineOptions: ['ASAP - I need help now', 'Within 1 month', '1-3 months', '3-6 months', 'Just exploring options'],
        formLabels: {
          contactMethodsTitle: 'Get in Touch',
          contactMethodsSubtitle: 'Ready to discuss your restaurant marketing goals? Choose the contact method that works best for you.',
          formTitle: 'Send us a message',
          formSubtitle: 'Fill out the form below and we\'ll get back to you within 24 hours with a customized strategy for your business.',
          firstName: 'First Name *',
          lastName: 'Last Name *',
          email: 'Email Address *',
          phone: 'Phone Number',
          company: 'Business Name *',
          businessType: 'Business Type *',
          budget: 'Marketing Budget',
          timeline: 'Timeline',
          goals: 'What are your main marketing goals? *',
          message: 'Additional Details',
          submitButton: 'Send Message & Get Free Consultation',
          privacyText: 'We respect your privacy and will never share your information.',
          placeholders: {
            firstName: 'Enter your first name',
            lastName: 'Enter your last name',
            email: 'your@email.com',
            phone: '(555) 123-4567',
            company: 'Your Business Name',
            businessType: 'Select your business type',
            budget: 'Select your budget range',
            timeline: 'When do you want to start?',
            goals: 'e.g., Increase foot traffic, boost online orders, improve local visibility...',
            message: 'Tell us more about your restaurant, current challenges, or any specific questions you have...'
          }
        },
        officeHours: {
          weekdays: '9:00 AM - 6:00 PM EST',
          saturday: '10:00 AM - 2:00 PM EST', 
          sunday: 'Closed',
          emergency: 'Emergency support available 24/7 for existing clients.',
        },
        faq: [
          {
            question: 'How quickly can I expect to see results?',
            answer: 'Most restaurant clients see initial improvements within 30-60 days, with significant foot traffic increases typically achieved within 3-6 months. The timeline depends on your current marketing foundation and campaign objectives.',
          },
          {
            question: 'Do you work with restaurants outside of these industries?',
            answer: 'We focus exclusively on hospitality, food service, healthcare, and athletics to provide the deepest expertise possible. This specialization allows us to deliver superior results compared to generalist agencies.',
          },
          {
            question: 'What makes your approach different for restaurants?',
            answer: 'Unlike generic marketing agencies, we understand the unique challenges of restaurant marketing, including local competition, delivery platforms, and customer retention. Our strategies are built on food service-specific insights and proven best practices.',
          },
          {
            question: 'Do you require long-term contracts?',
            answer: 'We offer both monthly and annual plans. While we recommend longer commitments for best results, we understand every restaurant has different needs and can work with you to find the right arrangement.',
          },
        ],
      },
    },
    metadata: {
      title: 'Restaurant Marketing Services - Inteligencia',
      description: 'Digital marketing services for restaurants and food service businesses. Increase customers with local SEO, social media, and online ordering optimization.',
      keywords: ['restaurant marketing', 'food service marketing', 'local seo', 'google my business', 'online ordering'],
    },
  },

  healthcare: {
    ...baseConfig,
    industry: 'healthcare',
    name: 'Dental & Healthcare Marketing',
    subdomain: 'dental',
    branding: {
      primaryColor: '#002643',
      secondaryColor: '#0093a0',
      accentColor: '#FFD700',
    },
    content: {
      hero: {
        title: 'Grow Your Practice with Quality Patients',
        subtitle: 'Attract new patients and build lasting relationships with HIPAA-compliant marketing',
        backgroundType: 'video',
        backgroundSrc: 'https://www.youtube.com/watch?v=cAyEiF7VzhY',
        ctaText: 'Get Free Practice Growth Analysis',
        ctaLink: '/contact',
        stats: [
          { value: '150+', label: 'New Patients per Month' },
          { value: '95%', label: 'Patient Retention Rate' },
          { value: '$2.8M', label: 'Additional Annual Revenue' },
        ],
      },
      services: [
        {
          title: 'Patient Acquisition Campaigns',
          description: 'Attract quality patients actively searching for dental services with HIPAA-compliant marketing.',
          keyBenefit: 'Average 120 new patients per month',
          icon: 'shield-check',
          learnMoreLink: '/services#patient-acquisition',
        },
        {
          title: 'Reputation Management',
          description: 'Build trust and credibility with 5-star reviews and professional online presence.',
          keyBenefit: '4.8+ star average rating',
          icon: 'search',
          learnMoreLink: '/services#reputation-management',
        },
        {
          title: 'Practice Growth Consulting',
          description: 'Strategic guidance and systems for sustainable practice expansion and profitability.',
          keyBenefit: 'Average 40% practice growth',
          icon: 'book-open',
          learnMoreLink: '/services#practice-growth',
        },
      ],
      team: [
        {
          name: 'Laurie Meiring',
          title: 'Founder & Healthcare Marketing Specialist',
          bio: 'Specializing in HIPAA-compliant marketing for healthcare providers, Laurie helps dental practices attract quality patients while maintaining the highest standards of privacy and professionalism.',
          certifications: ['Google Ads Certified', 'Healthcare Marketing Certified', 'HIPAA Compliance Expert'],
          image: '/images/team/laurie-meiring.jpg',
        },
      ],
      testimonials: [
        {
          quote: 'Laurie\'s patient acquisition campaigns brought us 150 new patients in our first 6 months working together. The quality of patients is exceptional, and our practice has never been busier.',
          author: 'Dr. Jennifer Chen',
          position: 'Practice Owner',
          company: 'Smile Dental Group',
        },
        {
          quote: 'The reputation management system Laurie implemented helped us achieve a 4.9-star rating across all platforms. New patients frequently mention finding us through positive reviews.',
          author: 'Dr. Michael Foster',
          position: 'Dental Practice Owner',
          company: 'Foster Family Dentistry',
        },
        {
          quote: 'Laurie\'s HIPAA-compliant campaigns brought quality patients who value our comprehensive care. Our practice revenue increased by $500K in the first year.',
          author: 'Dr. Amanda Williams',
          position: 'Practice Manager',
          company: 'Williams Dental Associates',
        },
      ],
      pricing: {
        plans: [
          {
            name: 'Practice Starter',
            price: '$1,500',
            duration: 'per month',
            description: 'Great for solo practitioners or small practices (1-2 dentists)',
            features: ['Patient acquisition campaigns', 'Review management', 'Basic compliance setup'],
            ctaText: 'Get Started',
            ctaLink: '/contact',
          },
          {
            name: 'Practice Growth',
            price: '$3,000',
            duration: 'per month',
            description: 'Ideal for multi-dentist practices or specialty dental services',
            features: ['Advanced patient acquisition', 'Reputation management suite', 'Practice growth consulting', 'Technology integration'],
            recommended: true,
            ctaText: 'Most Popular',
            ctaLink: '/contact',
          },
          {
            name: 'Practice Pro+',
            price: '$5,500',
            duration: 'per month',
            description: 'Perfect for large practices or dental organizations',
            features: ['Advanced practice management', 'Continuing education support', 'Strategic growth planning', 'Executive advisory services'],
            ctaText: 'Contact Us',
            ctaLink: '/contact',
          },
        ],
      },
      contact: {
        title: 'Ready to Grow Your Practice?',
        subtitle: 'Get your free practice growth analysis and discover how to attract quality patients with HIPAA-compliant marketing.',
        calendlyText: 'Schedule Your Free Practice Growth Consultation',
        email: 'dental@inteligencia.com',
        phone: '(555) 123-4567',
        address: '123 Business Ave, Suite 100, Miami, FL 33101',
        businessTypes: ['General Dentistry', 'Dental Speciality', 'Medical Practice', 'Urgent Care', 'Healthcare Group', 'Other'],
        budgetRanges: ['$1,000 - $2,500/month', '$2,500 - $5,000/month', '$5,000 - $10,000/month', '$10,000+ /month', 'Let\'s discuss'],
        timelineOptions: ['ASAP - I need help now', 'Within 1 month', '1-3 months', '3-6 months', 'Just exploring options'],
        formLabels: {
          contactMethodsTitle: 'Get in Touch',
          contactMethodsSubtitle: 'Ready to discuss your healthcare practice marketing goals? Choose the contact method that works best for you.',
          formTitle: 'Send us a message',
          formSubtitle: 'Fill out the form below and we\'ll get back to you within 24 hours with a customized strategy for your practice.',
          firstName: 'First Name *',
          lastName: 'Last Name *',
          email: 'Email Address *',
          phone: 'Phone Number',
          company: 'Practice Name *',
          businessType: 'Practice Type *',
          budget: 'Marketing Budget',
          timeline: 'Timeline',
          goals: 'What are your main practice goals? *',
          message: 'Additional Details',
          submitButton: 'Send Message & Get Free Consultation',
          privacyText: 'We respect your privacy and will never share your information. All communications are HIPAA-compliant.',
          placeholders: {
            firstName: 'Enter your first name',
            lastName: 'Enter your last name',
            email: 'your@email.com',
            phone: '(555) 123-4567',
            company: 'Your Practice Name',
            businessType: 'Select your practice type',
            budget: 'Select your budget range',
            timeline: 'When do you want to start?',
            goals: 'e.g., Attract new patients, improve online reputation, increase treatment acceptance...',
            message: 'Tell us more about your practice, current challenges, or any specific questions you have...'
          }
        },
        officeHours: {
          weekdays: '9:00 AM - 6:00 PM EST',
          saturday: '10:00 AM - 2:00 PM EST', 
          sunday: 'Closed',
          emergency: 'Emergency support available 24/7 for existing clients.',
        },
        faq: [
          {
            question: 'How quickly can I expect to see results?',
            answer: 'Most healthcare practices see initial improvements within 30-60 days, with significant patient acquisition typically achieved within 3-6 months. The timeline depends on your current marketing foundation and campaign objectives.',
          },
          {
            question: 'Do you work with practices outside of these industries?',
            answer: 'We focus exclusively on hospitality, food service, healthcare, and athletics to provide the deepest expertise possible. This specialization allows us to deliver superior results compared to generalist agencies.',
          },
          {
            question: 'Is your marketing HIPAA-compliant?',
            answer: 'Yes, all our healthcare marketing campaigns are fully HIPAA-compliant. We understand the unique privacy requirements of medical practices and ensure all patient information is protected according to federal regulations.',
          },
          {
            question: 'Do you require long-term contracts?',
            answer: 'We offer both monthly and annual plans. While we recommend longer commitments for best results, we understand every practice has different needs and can work with you to find the right arrangement.',
          },
        ],
      },
    },
    metadata: {
      title: 'Healthcare Marketing Services - Inteligencia',
      description: 'HIPAA-compliant digital marketing for dental and healthcare practices. Attract new patients with ethical, compliant marketing strategies.',
      keywords: ['healthcare marketing', 'dental marketing', 'hipaa compliant', 'medical marketing', 'patient acquisition'],
    },
  },

  athletics: {
    ...baseConfig,
    industry: 'athletics',
    name: 'Sports & Recreation Marketing',
    subdomain: 'sports',
    branding: {
      primaryColor: '#002643',
      secondaryColor: '#0093a0',
      accentColor: '#FFD700',
    },
    content: {
      hero: {
        title: 'Fill Your Courts, Grow Your Community',
        subtitle: 'Drive membership growth and tournament participation with sports marketing expertise',
        backgroundType: 'video',
        backgroundSrc: 'https://www.youtube.com/watch?v=cAyEiF7VzhY',
        ctaText: 'Get Free Facility Growth Plan',
        ctaLink: '/contact',
        stats: [
          { value: '200%', label: 'Tournament Participation Growth' },
          { value: '85%', label: 'Facility Utilization Rate' },
          { value: '300+', label: 'New Members This Year' },
        ],
      },
      services: [
        {
          title: 'Tournament & Event Promotion',
          description: 'Fill every tournament bracket and maximize event attendance with targeted marketing.',
          keyBenefit: 'Average 200% increase in participation',
          icon: 'trophy',
          learnMoreLink: '/services#tournament-promotion',
        },
        {
          title: 'Membership Growth Campaigns',
          description: 'Build a thriving sports community that keeps growing with strategic member acquisition.',
          keyBenefit: '300+ new members annually',
          icon: 'users',
          learnMoreLink: '/services#membership-growth',
        },
        {
          title: 'Facility Management & Analytics',
          description: 'Data-driven insights and optimization strategies to maximize facility performance.',
          keyBenefit: '20% increase in facility revenue',
          icon: 'calendar',
          learnMoreLink: '/services#facility-analytics',
        },
      ],
      team: [
        {
          name: 'Laurie Meiring',
          title: 'Founder & Sports Marketing Strategist',
          bio: 'An avid sports enthusiast and marketing expert, Laurie understands the unique challenges of recreational facilities and specializes in building vibrant sporting communities through targeted marketing campaigns.',
          certifications: ['Google Ads Certified', 'Sports Marketing Specialist', 'Event Promotion Expert'],
          image: '/images/team/laurie-meiring.jpg',
        },
      ],
      testimonials: [
        {
          quote: 'Since partnering with Inteligencia, our tournament participation has doubled and we\'ve added 300 new members. Laurie understands the sports community like no other marketer we\'ve worked with.',
          author: 'Mike Thompson',
          position: 'Facility Director',
          company: 'Central Coast Sports Complex',
        },
        {
          quote: 'Our facility utilization improved from 60% to 85% after implementing Laurie\'s membership growth strategies. The community engagement programs have been a game-changer.',
          author: 'Lisa Park',
          position: 'Operations Manager',
          company: 'Elite Sports Center',
        },
        {
          quote: 'The tournament promotion strategies Laurie developed helped us host our largest event ever with 500+ participants. The community response was overwhelming.',
          author: 'James Rodriguez',
          position: 'Event Coordinator',
          company: 'Coastal Recreation Complex',
        },
      ],
      pricing: {
        plans: [
          {
            name: 'Facility Basics',
            price: '$1,500',
            duration: 'per month',
            description: 'Perfect for single-court facilities or small recreational centers',
            features: ['Basic digital marketing setup', 'Membership growth campaigns', 'Event promotion support'],
            ctaText: 'Get Started',
            ctaLink: '/contact',
          },
          {
            name: 'Elite Facility',
            price: '$3,000',
            duration: 'per month',
            description: 'Great for multi-court facilities with tournaments and events',
            features: ['Comprehensive marketing strategy', 'Tournament promotion system', 'Advanced analytics dashboard', 'Community building programs'],
            recommended: true,
            ctaText: 'Most Popular',
            ctaLink: '/contact',
          },
          {
            name: 'Championship Package',
            price: '$5,500',
            duration: 'per month',
            description: 'Ideal for major recreational complexes or sports facilities',
            features: ['Full facility optimization', 'Professional tournament hosting', 'Sponsorship and partnership development', 'Custom facility development'],
            ctaText: 'Contact Us',
            ctaLink: '/contact',
          },
        ],
      },
      contact: {
        title: 'Ready to Build Your Sports Community?',
        subtitle: 'Get your free facility growth plan and learn how to maximize membership and tournament participation.',
        calendlyText: 'Schedule Your Free Facility Growth Consultation',
        email: 'sports@inteligencia.com',
        phone: '(555) 123-4567',
        address: '123 Business Ave, Suite 100, Miami, FL 33101',
        businessTypes: ['Tennis Club', 'Pickleball Facility', 'Golf Course', 'Fitness Center', 'Sports Complex', 'Recreation Center', 'Other'],
        budgetRanges: ['$1,000 - $2,500/month', '$2,500 - $5,000/month', '$5,000 - $10,000/month', '$10,000+ /month', 'Let\'s discuss'],
        timelineOptions: ['ASAP - I need help now', 'Within 1 month', '1-3 months', '3-6 months', 'Just exploring options'],
        formLabels: {
          contactMethodsTitle: 'Get in Touch',
          contactMethodsSubtitle: 'Ready to discuss your sports facility marketing goals? Choose the contact method that works best for you.',
          formTitle: 'Send us a message',
          formSubtitle: 'Fill out the form below and we\'ll get back to you within 24 hours with a customized strategy for your facility.',
          firstName: 'First Name *',
          lastName: 'Last Name *',
          email: 'Email Address *',
          phone: 'Phone Number',
          company: 'Facility Name *',
          businessType: 'Facility Type *',
          budget: 'Marketing Budget',
          timeline: 'Timeline',
          goals: 'What are your main facility goals? *',
          message: 'Additional Details',
          submitButton: 'Send Message & Get Free Consultation',
          privacyText: 'We respect your privacy and will never share your information.',
          placeholders: {
            firstName: 'Enter your first name',
            lastName: 'Enter your last name',
            email: 'your@email.com',
            phone: '(555) 123-4567',
            company: 'Your Facility Name',
            businessType: 'Select your facility type',
            budget: 'Select your budget range',
            timeline: 'When do you want to start?',
            goals: 'e.g., Increase membership, fill tournaments, boost facility utilization...',
            message: 'Tell us more about your facility, current challenges, or any specific questions you have...'
          }
        },
        officeHours: {
          weekdays: '9:00 AM - 6:00 PM EST',
          saturday: '10:00 AM - 2:00 PM EST', 
          sunday: 'Closed',
          emergency: 'Emergency support available 24/7 for existing clients.',
        },
        faq: [
          {
            question: 'How quickly can I expect to see results?',
            answer: 'Most sports facilities see initial improvements within 30-60 days, with significant membership growth typically achieved within 3-6 months. The timeline depends on your current marketing foundation and campaign objectives.',
          },
          {
            question: 'Do you work with facilities outside of these industries?',
            answer: 'We focus exclusively on hospitality, food service, healthcare, and athletics to provide the deepest expertise possible. This specialization allows us to deliver superior results compared to generalist agencies.',
          },
          {
            question: 'What makes your approach different for sports facilities?',
            answer: 'Unlike generic marketing agencies, we understand the unique challenges of sports facility marketing, including seasonal participation, community building, and event promotion. Our strategies are built on athletics-specific insights and proven best practices.',
          },
          {
            question: 'Do you require long-term contracts?',
            answer: 'We offer both monthly and annual plans. While we recommend longer commitments for best results, we understand every facility has different needs and can work with you to find the right arrangement.',
          },
        ],
      },
    },
    metadata: {
      title: 'Sports Marketing Services - Inteligencia',
      description: 'Digital marketing for sports facilities and athletic communities. Grow memberships, fill tournaments, and build engaged communities.',
      keywords: ['sports marketing', 'athletic facility marketing', 'tournament promotion', 'membership growth', 'sports community'],
    },
  },

  main: {
    ...baseConfig,
    industry: 'main',
    name: 'Inteligencia - Multi-Industry Marketing',
    subdomain: 'inteligencia',
    branding: {
      primaryColor: '#002643',
      secondaryColor: '#0093a0',
      accentColor: '#FFD700',
    },
    content: {
      hero: {
        title: 'Intelligent Marketing for Every Industry',
        subtitle: 'Choose your industry and discover specialized marketing solutions designed for your business.',
        backgroundType: 'image',
        backgroundSrc: '/images/main-hero-bg.jpg',
        ctaText: 'Choose Your Industry',
        ctaLink: '#industries',
      },
      services: [],
      team: [],
      testimonials: [],
      pricing: { plans: [] },
      contact: {
        title: 'Ready to Get Started?',
        subtitle: 'Contact us to discuss your industry-specific marketing needs.',
        email: 'info@inteligencia.com',
        phone: '(555) 123-4567',
      },
    },
    metadata: {
      title: 'Inteligencia - Specialized Marketing Solutions',
      description: 'Professional marketing services tailored for hotels, restaurants, healthcare, and sports industries. Choose your industry for specialized solutions.',
      keywords: ['digital marketing', 'industry marketing', 'specialized marketing', 'business growth', 'marketing solutions'],
    },
  },
};